### ISSUE TITLE
Finish MaterialUI migration to v5

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#2274] opened 2022-09-14 21:05 UTC
**Describe the task**
Part two of the migration will be removing the old Material UI libraries so that we're completely onboarded onto the `emotion` CSS engine that Material UI has moved to. We may need to migrate components one by one while testing their rendering and fixing any bugs that crop up

Basically perform the rest of the migration, starting from "Migrate from JSS" step in: https://mui.com/material-ui/guides/migration-v4/#migrate-from-jss
**Acceptance Criteria**
- [ ] All MaterialUI components in ASA are v5
- [ ] ASA UI renders properly

**Additional context**
- https://mui.com/material-ui/guides/migration-v4/#migrate-from-jss

**Comment by conbrad** [comment] 2023-06-21 19:48
Duplicate of: https://app.zenhub.com/workspaces/bcws---agile-psu-5e321393e038fba5bbe203b8/issues/gh/bcgov/wps/1898

**Closed by conbrad** 2023-06-21 19:48 UTC
Labels: Task
