### ISSUE TITLE
 Roles/Responsibility for Ticket Writing - (Sybrand end Oct)

### ISSUE THREAD

**Issue by NicolasLivanos** [bcgov/wps#2244] opened 2022-08-24 22:12 UTC
**Describe the task**
A clear and concise description of what the task is.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by Sybrand** [comment] 2022-08-24 22:20
Duplicate of #2238

**Closed by Sybrand** 2022-08-24 22:20 UTC
Labels: Task
