### ISSUE TITLE
weather station drop down populated by data from WF1 Phase 3 API

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#269] opened 2020-04-29 17:54 UTC
**As a** *Consultant/wildfire staff* **I want** *the weather station drop down to be up to date* **So That** *when I select a weather station I know it is based on the most recently available data*

**Acceptance Criteria**
- [x] Given I am attempting to select a weather station, When I search through the weather station list, Then the results are sourced based on the up to date data from the API
- [x] Connect calculator to Wildfire One Phase 3 API as the data source

**Additional Context**
- we dont require authentication our side for the weather stations
- enter text here

**Comment by jowand** [comment] 2020-04-29 19:12
Wait until after Thursday 2pm meeting with Selkirk Solutions to action this.

This ticket might be resolved by collaborating on what WildfireOne team has already done.

**Comment by Sybrand** [comment] 2020-05-06 16:23
@jowand  Is this a duplicate of https://app.zenhub.com/workspaces/wildfire-predictive-services-5e321393e038fba5bbe203b8/issues/bcgov/wps/271?

I've started looking at it on branch: feature/wf1_api_weather

**Closed** 2020-05-12 23:18 UTC
Labels: Ready, User Story
