### ISSUE TITLE
Empty rows break sorting; causes error in deleting

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/wps#1251] opened 2021-08-20 23:53 UTC
**Describe the Bug**
There's some conflict going on between empty rows, sorting, and row ids. The empty row you think you've selected is not actually the row you've selected.

**Expected Behaviour**
Given I'm in Firebat, When I click the checkbox on an empty row and click the "delete row" button, Then the row I selected should be the row that gets deleted.

**Actual Behaviour**
Some other row gets deleted instead. Hey I still wanted that one!

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to FireBAT
2. Add 2 rows with stations, fuel types, etc. selected & wait for data to be retrieved
3. Click the "Add row" button, leave the row empty
4. Sort the table by any column
5. Click the checkbox in the empty row, then click "Delete row" button
6. Once the page has refreshed, the empty row is still there; instead one of the rows with data in it has been deleted. Whomp-whomp.

**Screenshots**

**Additional context**

**Comment by conbrad** [comment] 2021-08-30 21:52
Cannot reproduce, most likely fixed before the inline table was deployed/merged.

**Closed by conbrad** 2021-08-30 21:52 UTC
Labels: Bug
