### ISSUE TITLE
1 day Temp forecast accuracy displayed on map

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#911] opened 2021-04-21 22:41 UTC
**As a** *Forecaster or Forecast lead* **I want** *to be able to look at the map and determine which weather stations have accurate Temp forecasts, which stations high/low forecasts* **So That** *I can target my efforts to improve my forecasting and learn how i am doing overall*

**Additional Context**
- warm (Red) colours mean the Temp was higher than forecasted, cool colours (blue) mean the Temp was lower than forecasted 
- if the data is missing it should not look like a "good" station, it should be noticeable, perhaps as black
- within 2 degree in either direction should be recognized as accurate, and then the colours should get darker in 2 degree increments
- https://miro.com/app/board/o9J_ktow2OY=/
- https://www.figma.com/file/2VuF3FNyhuf5gKD7jqEbeR/MoreCast?node-id=193%3A2
- want to see coloured dots at scale of Fire Centre (entire fire centre is visible in one screen - approx. 2 + clicks in)
- **this is a stormable ticket!!**

**Acceptance Criteria**
- [x] Given I am on the map, When I look at a weather station, Then I can tell how accurate the Temp forecast is for the today at any given weather station
- [x] Given I am on the map, When I look at a weather station that is missing either observed or forecast data, Then I can tell that the station i doesn't have the needed data to make an accuracy rating
- [x] if observed values arent available show the station as black
- [ ] Given I am on the test site (using WFWX API), When I refresh the map in Morecast, Then the accuracy of the stations' forecasts is immediately reflected *(this only applies if the WFWX API is performant)*
- [x] Given I am on the Morecast homepage, when I change the time of interest, then the map changes to reflect the the most recent forecast prior to the time of interest
- [x] given i am looking that the RH Accuracy map when i toggle to Temp the map updates to show the correct color scheme and data
- [x] in the legend have color gradient indicates 2 degrees

**Comment by Sybrand** [comment] 2021-04-21 22:48
I added the acceptance criteria re. it being clear to what date the points relate.

**Comment by andrea-williams** [comment] 2021-06-25 18:07
Bugs/enhancements discovered in our existing RH forecast accuracy feature that should also be addressed in this ticket:

- [ ] RH accuracy is being calculated using percent relative error, rather than 3 percentage points error (which is the expected behaviour)
- [ ] The "accurate" (neutral colour) on the legend should really be twice the width of the other squares, since any forecast within 3 percentage points either way of the observed is considered accurate (a 6 percentage point window), whereas the rest of the boxes in the gradient represent only 3 percentage points.

**Comment by andrea-williams** [comment] 2021-06-30 23:31
progress update: in dev, need to figure out why the change of state in selectedWxVariable is being emitted to the Legend component but not to the WeatherMap component (the state is stored in MoreCastPage). This means that the map isn't being updated when the wx variable is toggled.

I've been massively slowed down in working on this because something's going wrong in my local env, where the stations on the map only have observation data and no forecast data, even though the forecasts are appearing in my local DB. Need more time to troubleshoot what's going on there.

**Comment by conbrad** [comment] 2021-07-05 15:19
On Friday I managed to zone in on the issue and have a branch off the PR whose diff creates the desired behaviour: https://github.com/bcgov/wps/pull/1085

The issue was not React related, but some complexity around how and when OpenLayers re-renders vector layers, as well as potentially a javascript closure holding on to a non updated reference to the selectedWxVariable.

**Comment by andrea-williams** [comment] 2021-09-02 23:28
Progress update:

- code is currently not working in PR's dev env. All dots on map showing up as black; the backend is only returning forecasts for stations 212, 222, & 316 (and not observations for those stations). The rest of the stations only have observations, no forecasts. I've tried sending the same URL request to WFWX via Postman and get the same result. Don't know the cause. This also happens in my local, but not in prod. AFAIK no changes have been made to the query sent to WFWX. When I set `use_wfwx` to `False` in my local, I do start seeing results in the map.
- I suspect that there's a flaw in the math/logic for calculating station accuracy: when I was running locally and not using WFWX, I noticed that all the dots on the station map were either neutral colours (that's fine), or they were from the left side of the colour gradient (for both temp & RH). Observed this for multiple days, everywhere in BC. This seems highly unlikely to be correct.

**Closed** 2021-09-08 20:05 UTC
Labels: User Story, Ready
